name: Backend

on:
  push:
    branches: [ master ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Build Spring Boot App
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./backend
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./backend
      env:
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

    # Build Image and push to Azure
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: ggconreg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build backend/. -t ggconreg.azurecr.io/backend:${{ github.sha }}
        docker push ggconreg.azurecr.io/backend:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'ggbackend'
        images: 'ggconreg.azurecr.io/backend:${{ github.sha }}'
