name: Frontend
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: ggconreg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build app/. -t ggconreg.azurecr.io/frontend:${{ github.sha }}
        docker push ggconreg.azurecr.io/frontend:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'ggfrontend'
        images: 'ggconreg.azurecr.io/frontend:${{ github.sha }}'
